[versions]
kotlin = "2.2.0"
compose = "1.8.2"

arrow = "2.1.2"

# ANDROID
agp = "8.11.0"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"

androidx-lifecycle = "2.9.1"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

android-library = { id = "com.android.library", version.ref = "agp" }

vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }

[libraries]

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
